services:
  meAI-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meAI-be
    env_file:
      - .env
    depends_on:
      - db
      - chromadb
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/app

  meAI-db:
    image: postgres:15
    container_name: meAI-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  meAI-chromadb:
    image: chromadb/chroma:latest
    container_name: meAI-chromadb
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - chroma_data:/chroma

volumes:
  postgres_data:
  chroma_data:
