"""adds fields for password and auth_method

Revision ID: 5065b21062c3
Revises: c0d391c91b2f
Create Date: 2025-07-19 12:05:33.652340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5065b21062c3'
down_revision: Union[str, Sequence[str], None] = 'c0d391c91b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_method', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'password')
    op.drop_column('users', 'auth_method')
    # ### end Alembic commands ###
