"""updates conversation model to also have conversation summary of last n messages for having a better overall context of the conversation.

Revision ID: 5cab1373b32e
Revises: a8e08f41a796
Create Date: 2025-07-19 18:39:09.391735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cab1373b32e'
down_revision: Union[str, Sequence[str], None] = 'a8e08f41a796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary_text')
    # ### end Alembic commands ###
